INSERT INTO listings (
    host_id,
    location_id,
    title,
    description,
    listing_type,
    status,
    total_rooms,
    available_rooms,
    max_occupants,
    is_furnished,
    allows_pets,
    allows_smoking,
    price_per_month,
    currency,
    security_deposit,
    utilities_included,
    utility_details,
    available_from,
    min_stay_days
)
VALUES
(
    'cccccccc-cccc-cccc-cccc-cccccccccccc',
    '11111111-1111-1111-1111-111111111111',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Fully Furnished Private Room in CBD',
    'Spacious private room with attached bathroom and balcony access.',
    'private_room',
    'active',
    3,
    1,
    2,
    TRUE,
    FALSE,
    FALSE,
    18000.00,
    'INR',
    18000.00,
    TRUE,
    '{"water": true, "electricity": true, "wifi": true}',
    '2026-03-01',
    30
)